name: Docker Image CI

on:
  push:
    branches: [ "build" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set lowercased author as env
      run: |
        echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> "${GITHUB_ENV}"

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 如有需要可修改为你的 maim_message fork
    - name: Clone maim_message
      run: git clone https://github.com/MaiM-with-u/maim_message maim_message

    - name: Determine Image Tags
      id: tags
      run: |
        if [ "${GITHUB_REF_NAME}" = "build" ]; then
          DATE_TAG=$(date -u +'%Y-%m-%dT%H-%M-%S')
          TAGS="ghcr.io/${REPO_OWNER_LC}/maimbot-adapter:latest,ghcr.io/${REPO_OWNER_LC}/maimbot-adapter:build-$(date -u +'%Y%m%d%H%M%S')"
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
          echo "date_tag=$DATE_TAG" >> $GITHUB_OUTPUT
        fi

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.tags.outputs.tags }}
        push: true
        cache-from: type=registry,ref=ghcr.io/${{ env.REPO_OWNER_LC }}/maimbot-adapter:buildcache-build
        cache-to: type=registry,ref=ghcr.io/${{ env.REPO_OWNER_LC }}/maimbot-adapter:buildcache-build,mode=max
        labels: |
          org.opencontainers.image.created=${{ steps.tags.outputs.date_tag }}
          org.opencontainers.image.revision=${{ github.sha }}